sudo: required

services:
  - docker

before_install:
  - docker build -t lexyblazy/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run lexyblazy/react-test npm run test:ci

after_success:
  - docker build -t lexyblazy/multi-client ./client
  - docker build -t lexyblazy/multi-nginx ./nginx
  - docker build -t lexyblazy/multi-server ./server
  - docker build -t lexyblazy/multi-worker ./worker

  # login to dockerhub
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  # push images to dockerhub
  - docker push lexyblazy/multi-client
  - docker push lexyblazy/multi-nginx
  - docker push lexyblazy/multi-server
  - docker push lexyblazy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-017908065641"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
