sudo: required

services:
  - docker

before_install:
  - docker build -t lexyblazy/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run lexyblazy/react-test npm run test:ci

after_success:
  - docker build -t lexyblazy/multi-client:latest ./client
  - docker build -t lexyblazy/multi-nginx:latest ./nginx
  - docker build -t lexyblazy/multi-server:latest ./server
  - docker build -t lexyblazy/multi-worker:latest ./worker

  # login to dockerhub
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  # push images to dockerhub
  - docker push lexyblazy/multi-client:latest
  - docker push lexyblazy/multi-nginx:latest
  - docker push lexyblazy/multi-server:latest
  - docker push lexyblazy/multi-worker:latest
